Repository sonalyze/aal-backend, pull requests merged in 2025-06, with the labels that each got.

#64 flatlined logging
  src/api/endpoints/measurement_routes.py
  src/api/endpoints/room_routes.py
  src/api/endpoints/user_routes.py
  src/api/router.py
  src/main.py
  src/services/auth_service.py
  src/services/get_material.py
  src/services/measurement_service.py
  src/services/simulation_service.py
  src/sio/events/lobby_events.py
  src/sio/events/measurement_events.py
  src/sio/socketio_server.py
  src/sio/socketio_server.pyi
Labels: documentation

#76 Feature/measurement settings
  src/services/measurement_service.py
  src/sio/events/lobby_events.py
  src/sio/events/measurement_events.py
  src/sio/models.py
Labels: enhancement, architecture / design

#79 Add user_id mapping to LobbyClient and connection flow
  src/services/measurement_service.py
  src/sio/events/lobby_events.py
  src/sio/models.py
  src/sio/socketio_server.py
Labels: enhancement

#80 Added ffmpeg to docker build
  Dockerfile
Labels: architecture / design

#81 Update measurement_service.py
  src/services/measurement_service.py
Labels: architecture / design

#84 changed loop condition, save results to db
  src/services/measurement_service.py
Labels: enhancement

#91 Added analysis to simulation
  src/services/analysis_service.py
  src/services/measurement_service.py
  src/services/simulation_service.py
Labels: enhancement
